### ISSUE TITLE
Add your information to controllers.js

### ISSUE THREAD

**Issue by MicahRamirez** [kristinedomingo/cs373-idb#2]
Please add your bio to the google doc!

https://docs.google.com/document/d/1oEZvWJxevSlsqJqE6-IdXiiBj767rUCLv6Zcn23kiWs/edit?usp=sharing

@dabrego22 @kristinedomingo @jorgmuno

**Comment by kristinedomingo** [comment]
I'm like 90% sure it's possible to load GitHub stats (number of commits, issues) dynamically through the GitHub API, ima try to do this

**Comment by MicahRamirez** [comment]
OK Yeah that'd be cool
