### ISSUE TITLE
Improve CSS loading times (see coment)

### ISSUE THREAD

**Issue by kristinedomingo** [kristinedomingo/cs373-idb#49]
App.js is loaded at the end (which is should be), but since it loads the CSS as well, the user can be left staring at an almost blank white page w/ blue text out of place for 1-3 seconds, depending on internet speed. For example, clear your browser's cache and go to [http://www.sweetmusic.me/#/artists](http://www.sweetmusic.me/#/artists). The CSS is loaded **_after**_ the data in the table, which can take a while, especially since on Artists, two different API requests are made for each row.

Solution: since a lot of the stylesheets are the same up to the end (customized styles for each page), have a "base.css" that's link href'ed on base.html. Then, the individual stylesheets will just contain the customized styles for each page.

**Comment by MicahRamirez** [comment]
Good catch. I didn't even think of the repercussions of having angular load css dynamically.
