### ISSUE TITLE
Refactor Nav Styling and Clean it up 

### ISSUE THREAD

**Issue by MicahRamirez** [kristinedomingo/cs373-idb#98]
Need to position add relative positing so that everything is in line.

**Comment by kristinedomingo** [comment]
When you close this issue can you also re-add the space between the nav-bar and the rest of the page (like the page content is slightly under the nav bar, compare 0.0.0.0:5000/#/ildb to sweetmusic.me/#/ildb)? Also match the colors and style of the search bar to the one on the splash page (if you go to any other page that's not the splash page the search button is white, and the borders around the input box and search is blue when you click on them). Bootstrap also has a class "input-group-sm" to add to the input group, adding that to the nav search bar would make it match the size of the one on the splash page
